### ISSUE TITLE
"Automattic  \  WooCommerce  \  HttpClient  \  HttpClientException" PHP 8.1.2-1ubuntu2.14 10.24.0 cURL Error:

### ISSUE THREAD

**Issue by alexworldbr** [devfaysal/crm#1]
Hi @devfaysal !

I like this idea of form/page.

I tryed you code, but have a uknow error:

"Automattic \ WooCommerce \ HttpClient \ HttpClientException"

 cURL Error:

See print: [https://ibb.co/wC7Kcfs](https://ibb.co/wC7Kcfs)

Do you know the fix?

Tks

Alex

**Comment by devfaysal** [comment]
This actually requires the API key of your WooCommerce website.

At the bottom of the env file, you will see
```
TECHPLATOON_BASE_URL=
TECHPLATOON_KEY=
TECHPLATOON_SECRET=
```
TECHPLATOON_BASE_URL is you website URL e.g https://example.com
Key and secret can be found in the WooCommerce Settings of your website
![2023-09-21-20-15-54](https://github.com/devfaysal/crm/assets/16212149/32b270de-bd39-47dd-95c1-f160609a2409)

**Comment by alexworldbr** [comment]
Oh Yes.

I think was a code issue, since it's just a demo.

Thanks!

Att,

Alex
